[workspace]
authors = ["Mrugakshi Chidrawar <mrugakshi77@gmail.com>"]
channels = ["conda-forge"]
name = "pss-biomarker"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r-irkernel = ">=1.3.2,<2"
r = ">=4.5,<4.6"
r-seurat = ">=5.4.0,<6"
r-ggplot2 = ">=4.0.2,<5"
r-dplyr = ">=1.2.0,<2"
r-tidyr = ">=1.3.2,<2"
jupyter = ">=1.1.1,<2"
jupyterlab = ">=4.5.4,<5"
r-devtools = ">=2.4.6,<3"
r-usethis = ">=3.2.1,<4"
r-pkgbuild = ">=1.4.8,<2"
r-processx = ">=3.8.6,<4"
r-callr = ">=3.7.6,<4"
r-pheatmap = ">=1.0.13,<2"
